#!/bin/bash

function delete_local_merged_master_branches() {
  git branch --merged master | grep -v master | xargs git branch -d
}

function delete_local_merged_develop_branches() {
  git branch --merged develop | grep -v develop | xargs git branch -d
}

function delete_remote_merged_branches() {
  for BRANCH in `git branch -r --merged origin/master |\
                 grep -v master |\
                 cut -d/ -f2-`
  do
    git push origin :$BRANCH
  done
}

function fzf_branch() {
  # git for-each-ref --sort=committerdate /refs/heads/ --format='%(refname:short)' | fzf --tac | xargs git checkout
  git for-each-ref --sort=committerdate refs/heads/ --format='%(refname:short)' | fzf --tac | xargs git checkout

  # git branch | fzf --tac | xargs git checkout
}
